### PR TITLE
Upgrade to Elm 0.19

### PR DESCRIPTION
**Pull request by dillonkearns**
Hello there! I believe this is all ready to go to be published in Elm 0.19. The demo is compiling and looking good. Thanks for the cool package! 😄

### CODE REVIEW

**Comment by tripokey** [comment]
Thanks a lot!

Just waiting for https://github.com/NixOS/nixpkgs/pull/45448 to be merged for the travis-ci job.

**Comment by dillonkearns** [comment]
👍 Sounds good, it looks like they're getting close.

**Comment by garbas** [comment]
kinda sucks you took elm 0.18 away. now those of us who use 0.18 are stuck on old nixos.
but thank you for taking time to work on elm 0.19.
:)

**Comment by tripokey** [comment]
The elm 0.18 version is still available in earlier commits. Why would you be stuck on old nixos?

**Pull request merged**
